{
    "name": "OpenG2P Task",
    "version": "1.1",
    "category": "Project",
    "sequence": 10,
    "summary": "Organize and schedule your projects ",
    "depends": [],
    "description": "",
    "data": [
        "views/openg2p_task_status.xml",
        "views/openg2p_task_role.xml",
        "views/openg2p_task_type.xml",
        "views/openg2p_task_subtype.xml",
        "views/openg2p_task.xml",
        "views/openg2p_task_history.xml",
        "views/action.xml",
        "views/menu.xml",
        "data/openg2p_tasks_data.xml",
    ],
    "demo": [],
    "installable": True,
    "auto_install": False,
    "application": True,
}
